/*
 * XenForo album_sortable.min.js
 * Copyright 2010-2015 XenForo Ltd.
 * Released under the XenForo License Agreement: http://xenforo.com/license-agreement
 */
(function(a){XenForo.XenGallerySortable=function(a){this.__construct(a)};XenForo.XenGallerySortable.prototype={__construct:function(o){this.container=o;o.sortable({forcePlaceholderSize:!0}).bind({sortupdate:function(){},dragstart:function(a){console.log("drag start, %o",a.target)},dragend:function(){console.log("drag end");a(".Sort").removeClass("desc asc selected")}});a(".Sort").bind({click:a.context(this,"sortListPrep")})},sortListPrep:function(o){o.preventDefault();$target=this.container.data("sort-target");
$sort=a(o.target);$direction=$sort.data("sort-direction");a(".Sort").each(function(){a(this).data("sort-direction","asc");a(this).removeClass("desc asc selected")});$direction=="desc"?($altDirection="asc",$sort.data("sort-direction",$altDirection),$sort.removeClass($altDirection),$sort.addClass($direction+" selected")):$direction=="asc"&&($altDirection="desc",$sort.data("sort-direction",$altDirection),$sort.removeClass($altDirection),$sort.addClass($direction),$sort.addClass($direction+" selected"));
a($target).tsort({data:$sort.data("sort-type"),order:$direction})}};XenForo.register(".Sortable","XenForo.XenGallerySortable")})(jQuery,this,document);
(function(a,o){function D(b,a){for(var d=0,c=b.length;d<c;d++)if(b[d]==a)return!f;return f}var f=!1,v=parseFloat,E=Math.min,F=/(-?\d+\.?\d*)$/g,G=/(\d+\.?\d*)$/g,w=[],x=[],q=function(b,a){for(var d=b.length,c=d,f;c--;)f=d-c-1,a(b[f],f)},y=Array.prototype.indexOf||function(a,f){var d=this.length,c=Number(f)||0,c=c<0?Math.ceil(c):Math.floor(c);for(c<0&&(c+=d);c<d;c++)if(c in this&&this[c]===a)return c;return-1};a.tinysort={id:"TinySort",version:"1.5.6",copyright:"Copyright (c) 2008-2013 Ron Valstar",
uri:"http://tinysort.sjeiti.com/",licensed:{MIT:"http://www.opensource.org/licenses/mit-license.php"},plugin:function(){var a=function(a,b){w.push(a);x.push(b)};a.indexOf=y;return a}(),defaults:{order:"asc",attr:null,data:null,useVal:f,place:"start",returns:f,cases:f,forceStrings:f,ignoreDashes:f,sortFunction:null}};a.fn.extend({tinysort:function(){var b,t,d,c=[],s=[],z=[],u=[],p=0,r,j=[],k=[],H=function(a){q(w,function(b){b.call(b,a)})},A=function(a,b){typeof b=="string"&&(a.cases||(b=b&&b.toLowerCase?
b.toLowerCase():b),b=b.replace(/^\s*(.*?)\s*$/i,"$1"));return b},I=function(a,b){var c=0;for(p!==0&&(p=0);c===0&&p<r;){var d=u[p],g=d.oSettings,l=g.ignoreDashes?G:F;H(g);if(g.sortFunction)c=g.sortFunction(a,b);else if(g.order=="rand")c=Math.random()<0.5?1:-1;else{var e=f,h=A(g,a.s[p]),m=A(g,b.s[p]);if(!g.forceStrings&&(g=typeof h=="string"?h&&h.match(l):f,l=typeof m=="string"?m&&m.match(l):f,g&&l)){var j=h.substr(0,h.length-g[0].length),i=m.substr(0,m.length-l[0].length);j==i&&(e=!f,h=v(g[0]),m=v(l[0]))}c=
d.iAsc*(h<m?-1:h>m?1:0)}q(x,function(a){c=a.call(a,e,h,m,c)});c===0&&p++}return c};for(b=0,d=arguments.length;b<d;b++){var i=arguments[b];if(typeof i=="string"){if(j.push(i)-1>k.length)k.length=j.length-1}else if(k.push(i)>j.length)j.length=k.length}if(j.length>k.length)k.length=j.length;r=j.length;if(r===0)r=j.length=1,k.push({});for(b=0,d=r;b<d;b++){var i=j[b],n=a.extend({},a.tinysort.defaults,k[b]),B=!(!i||i===""),C=B&&i[0]===":";u.push({sFind:i,oSettings:n,bFind:B,bAttr:!(n.attr===null||n.attr===
""),bData:n.data!==null,bFilter:C,$Filter:C?this.filter(i):this,fnSort:n.sortFunction,iAsc:n.order=="asc"?1:-1})}this.each(function(b,c){var f=a(c),d=f.parent().get(0),g,l=[];for(t=0;t<r;t++){var e=u[t],h=e.bFind?e.bFilter?e.$Filter.filter(c):f.find(e.sFind):f;l.push(e.bData?h.data(e.oSettings.data):e.bAttr?h.attr(e.oSettings.attr):e.oSettings.useVal?h.val():h.text());g===o&&(g=h)}e=y.call(z,d);e<0&&(e=z.push(d)-1,s[e]={s:[],n:[]});g.length>0?s[e].s.push({s:l,e:f,n:b}):s[e].n.push({e:f,n:b})});q(s,
function(a){a.s.sort(I)});q(s,function(a){var d=a.s,a=a.n,j=d.length,i=a.length,g=j+i,l=[],e=g,h=[0,0];switch(n.place){case "first":q(d,function(a){e=E(e,a.n)});break;case "org":q(d,function(a){l.push(a.n)});break;case "end":e=i;break;default:e=0}for(b=0;b<g;b++){var m=(i=D(l,b)?!f:b>=e&&b<e+j)?0:1,k=(i?d:a)[h[m]].e;k.parent().append(k);(i||!n.returns)&&c.push(k.get(0));h[m]++}});this.length=0;Array.prototype.push.apply(this,c);return this}});a.fn.TinySort=a.fn.Tinysort=a.fn.tsort=a.fn.tinysort})(jQuery);
