/*
 * XenForo album_thumbs.min.js
 * Copyright 2010-2015 XenForo Ltd.
 * Released under the XenForo License Agreement: http://xenforo.com/license-agreement
 */
(function(){XenForo.MediaGallery={AlbumThumbs:function(b){b.flickbook({images:b.data("images"),speed:b.data("speed")?b.data("speed"):700,keepOriginalImage:b.data("keeporig")?b.data("keeporig"):!0,onStop:b.data("onstop")?b.data("onstop"):"reset",random:b.data("random")?b.data("random"):!1})}};XenForo.register(".AlbumThumbs","XenForo.MediaGallery.AlbumThumbs")})(jQuery,this,document);
(function(b){function d(a,e){this.el=a;this.$el=b(a);this.opts=e;this._name=c;this.init()}function i(a){var e=a.startEvent.split(" ").sort(),b=a.stopEvent.split(" ").sort(),c=[],d=[],g=0,j=e.length;a:for(;g<j;g++){for(var h=0,f=b.length;h<f;h++)if(e[g]===b[h]){d.push(e[g]);b.splice(h,1);continue a}c.push(e[g])}a.startEvent=c.join(" ");a.stopEvent=b.join(" ");a.stopStartEvent=d.join(" ")}var c="flickbook",f=b.fn.on?"on":"bind";d.prototype.playing=!1;d.prototype.index=-1;d.prototype.init=function(){var a=
this,e=this.$el.data(c+"-images");this.imageSrcs=e?e:b.isArray(this.opts.images)?this.opts.images.slice():this.opts.images;typeof this.imageSrcs==="string"?this.imageSrcs=this.imageSrcs.split(","):this.imageSrcs&&!b.isArray(this.imageSrcs)&&typeof this.imageSrcs==="object"&&this.imageSrcs.start&&this.imageSrcs.end&&this._getImageIndexesFromRange();!b.isArray(this.imageSrcs)||!this.imageSrcs.length?this.aborted=!0:(this.imageCount=this.imageSrcs.length,this.fetchImages(),this.$el.data(c+"-images",
this.images),this.$el[f]("start."+c,b.proxy(this,"start"))[f]("stop."+c,b.proxy(this,"stop"))[f](this.opts.stopEvent,function(){a.$el.trigger("stop."+c)})[f](this.opts.startEvent,function(){a.$el.trigger("start."+c)})[f](this.opts.stopStartEvent,function(){a.playing?a.$el.trigger("stop."+c):a.$el.trigger("start."+c)}),this.opts.autoStart&&this.start())};d.prototype._getImageIndexesFromRange=function(){for(var a=this,b=function(){var b=a.imageSrcs.padTo;return b?function(a){a+="";var e=b-a.length;
if(e)for(;e--;)a="0"+a;return a}:function(a){return a+""}}(),c=this.imageSrcs.end,d=[],f=this.imageSrcs.start;f<=c;f++)d.push(b(f));this.imageSrcs=d};d.prototype.start=function(){var a=this,b;if(!this.playing)this.to=setInterval(function(){if(a.opts.random)for(b=a.index;b===a.index;)a.index=Math.floor(Math.random()*a.imageCount);else a.index=(a.index+1)%a.imageCount;a.showImage()},this.opts.speed),this.playing=!0};d.prototype.stop=function(){if(this.playing){clearInterval(this.to);if(this.opts.onStop===
"reset")this.index=0;this.showImage();this.playing=!1}};d.prototype.showImage=function(){for(var a=0;!this.images[this.index]&&a<this.imageCount;)this.index=(this.index+1)%this.imageCount,a++;this.$el.attr("src",this.images[this.index])};d.prototype.loadImage=function(a,e){var c=this;b('<img src="'+c.imageSrcs[a]+'">').load(function(){c.images[a+e]=c.imageSrcs[a];b.fn.flickbook.fetchedImages[c.imageSrcs[a]]=!0})};d.prototype.processImageSrcs=function(){for(var a=this,b=function(){return a.opts.imageTemplate.match("{{}}")?
function(b){return a.opts.imageTemplate.replace("{{}}",b)}:function(b){return a.opts.imageTemplate+b}}(),c=0,d=this.imageCount;c<d;c++)this.imageSrcs[c]=b(this.imageSrcs[c])};d.prototype.fetchImages=function(){var a=0,c=this.$el.attr("src");this.images=[];this.opts.imageTemplate&&this.processImageSrcs();this.opts.keepOriginalImage&&c!==this.imageSrcs[0]&&(this.images[0]=c,b.fn.flickbook.fetchedImages[c]=!0,a=1);for(var c=0,d=this.imageSrcs.length;c<d;c++)b.fn.flickbook.fetchedImages[this.imageSrcs[c]]?
this.images[c+a]=this.imageSrcs[c]:this.loadImage(c,a)};b.fn[c]=function(a){a=b.extend({},b.fn[c].defaults,a);i(a);return this.each(function(){var e;b.data(this,"plugin_"+c)||(e=new d(this,a),e.aborted||b.data(this,"plugin_"+c,e))})};b.fn[c].fetchedImages={};b.fn[c].defaults={images:null,speed:100,imageTemplate:"",startEvent:"mouseover",stopEvent:"mouseout",autoStart:!1,onStop:"reset",keepOriginalImage:!1,random:!1}})(jQuery,window,document);
