/*
 * XenForo media_upload.min.js
 * Copyright 2010-2015 XenForo Ltd.
 * Released under the XenForo License Agreement: http://xenforo.com/license-agreement
 */
(function(d,m,k){XenForo.MediaGallery={SetAllImageTitles:function(a){a.click(function(){$titles=d("#SetAllImageTitleText").val();d("#SetAllImageTitleText").val("");$titles&&d(".SetImageTitle").each(function(a,b){var c=d(b),c=$titles.replace("%f",c.data("filename")),c=c.replace("%n",a+1);d(this).val(c)})})},SetAllImageDescriptions:function(a){a.click(function(){this.titles=d("#SetAllImageDescriptionText").val();d("#SetAllImageDescriptionText").val("");this.titles&&d(".SetImageDescription").val(this.titles)})},
SetAllVideoTitles:function(a){a.click(function(){this.titles=d("#SetAllVideoTitleText").val();d("#SetAllVideoTitleText").val("");this.titles&&d(".SetVideoTitle").val(this.titles)})},SetAllVideoDescriptions:function(a){a.click(function(){this.titles=d("#SetAllVideoDescriptionText").val();d("#SetAllVideoDescriptionText").val("");this.titles&&d(".SetVideoDescription").val(this.titles)})},InsertFilename:function(a){a.click(function(f){f.preventDefault();var f=a.data("filename"),b=a.data("target");d(b).val(f)})}};
XenForo.SetAllTitlesForm=function(a){a.closest("form").submit(function(a){a.preventDefault();return!1});a.overlay().close()};var i=XenForo.speed.normal,g=XenForo.speed.fast;XenForo.AttachmentDownloader=function(a){this.__construct(a)};XenForo.AttachmentDownloader.prototype={__construct:function(a){this.$input=a;this.url=a.data("href");this.uniqueKey=a.data("key");d(".DownloadTrigger").bind({click:d.context(this,"doDownload")})},doDownload:function(a){a.preventDefault();this.xhr=XenForo.ajax(this.url,
{image_url:this.$input.val()},d.context(this,"ajaxSuccess"),{error:"failure"});this.$input.val("")},ajaxSuccess:function(a){if(a.error){var f="";d.each(a.error,function(a,c){f+=c+"\n"});XenForo.alert(f);return!1}$container=d("#AttachmentUploader_image_upload");$container.trigger({type:"AttachmentUploaded",ajaxData:a})}};XenForo.AttachmentUploader=function(a){var f=d(a.data("trigger"));a.closest("form");var b=d(a.data("placeholder")),c={},e=null,h=null,j=a.data("maxfilesize");a.data("maxuploads");
var l=a.data("extensions"),g=a.data("uniquekey");this.uniqueKey=g;a.show();var i=XenForo.canonicalizeUrl(a.data("flashurl")||"js/swfupload/Flash/swfupload.swf");console.info("flash url: %s",i);typeof SWFUpload=="function"&&!m.navigator.userAgent.match(/Android|iOS|iPhone|iPad|Mobile Safari|Trident\/7.0/i)&&(e=new SWFUpload({upload_url:a.data("action"),file_post_name:a.data("postname"),file_types:"*."+(l.toLowerCase()+","+l.toUpperCase()).replace(/,/g,";*."),post_params:d.extend({_xfToken:XenForo._csrfToken,
_xfNoRedirect:1,_xfResponseType:"json"},c),button_placeholder_id:b.attr("id"),button_width:1,button_height:1,button_window_mode:SWFUpload.WINDOW_MODE.TRANSPARENT,button_cursor:SWFUpload.CURSOR.HAND,flash_url:i,prevent_swf_caching:!1,swfupload_loaded_handler:function(){this.setButtonDimensions(f.outerWidth(),f.outerHeight());a.find(".HiddenInput").each(function(a,b){e.addPostParam(d(b).data("name"),d(b).data("value"))});d(k).bind("CSRFRefresh",function(a){a.ajaxData&&(e.addPostParam("_xfToken",a.ajaxData.csrfToken),
e.addPostParam("_xfSessionId",a.ajaxData.sessionId))})},file_dialog_complete_handler:function(){try{this.getStats().files_queued>0&&this.startUpload(this.getFile(0).ID)}catch(a){this.debug(a)}},file_queued_handler:function(b){var c;switch(b.name.substr(b.name.lastIndexOf(".")).toLowerCase()){case ".jpg":case ".jpeg":case ".jpe":case ".png":case ".gif":c=!0;break;default:c=!1}var e=d.Event("AttachmentQueueValidation");e.file=b;e.swfUpload=this;e.isImage=c;a.trigger(e);if(!e.isDefaultPrevented())j>
0&&b.size>j&&!c?(this.cancelUpload(b.id,!1),typeof this.settings.file_queue_error_handler=="function"&&this.settings.file_queue_error_handler.call(this,b,SWFUpload.QUEUE_ERROR.FILE_EXCEEDS_SIZE_LIMIT,"The uploaded file is too large.")):(e=d.Event("AttachmentQueued"),e.file=b,e.swfUpload=this,e.isImage=c,a.trigger(e))},file_queue_error_handler:function(b,c,e){var f=d.Event("AttachmentQueueError");f.file=b;f.errorCode=c;f.message=e;f.swfUpload=this;a.trigger(f);f.isDefaultPrevented()||h(b,c,e)},upload_start_handler:function(a){console.log("Uploading %s",
a.name)},upload_progress_handler:function(b,c){a.trigger({type:"AttachmentUploadProgress",file:b,bytes:c,swfUpload:this})},upload_success_handler:function(b,c){try{var e=d.parseJSON(c)}catch(f){console.warn(f);return}e.error?a.trigger({type:"AttachmentUploadError",file:b,ajaxData:e,swfUpload:this}):a.trigger({type:"AttachmentUploaded",file:b,ajaxData:e,swfUpload:this})},upload_error_handler:function(b,c,e){c!=SWFUpload.UPLOAD_ERROR.FILE_CANCELLED&&(console.warn("Upload failed: %o",arguments),a.trigger({type:"AttachmentUploadError",
file:b,errorCode:c,message:e,ajaxData:{error:[a.data("err-unknown")]},swfUpload:this}))},upload_complete_handler:function(){try{this.getStats().files_queued>0?this.startUpload(this.getFile(0).ID):console.info("All files uploaded.")}catch(a){this.debug(a)}}}),h=function(b,c,e){c=a.data("err"+c)||e;b?XenForo.alert(c+"<br /><br />"+b.name):XenForo.alert(c)});d(k).bind("AutoInlineUploadComplete",function(b){if(g&&b.ajaxData&&g!==b.ajaxData.key)return!1;if(d(b.target).is("form.AttachmentUploadForm"))return f.overlay()&&
f.overlay().close(),a.trigger({type:"AttachmentUploaded",ajaxData:b.ajaxData}),!1});return{getSwfUploader:function(){return e},swfAlert:h}};XenForo.AttachmentEditor=function(a){this.setVisibility=function(b){var c=a.closest(".ctrlUnit"),e=a.find(".AttachmentInsertAllBlock"),d=a.find(".AttachedFile:not(#AttachedFileTemplate)"),f=d.filter(".AttachedImage");console.log("Attachments changed, total files: %d, images: %d",d.length,f.length);c.length==0&&(c=a);b===!0?d.length?(f.length>1?e.show():e.hide(),
c.show()):c.hide():d.length?(f.length>1?c.is(":hidden")?e.show():e.xfFadeDown(XenForo.speed.fast):c.is(":hidden")?e.hide():e.xfFadeUp(XenForo.speed.fast,!1,XenForo.speed.fast,"swing"),c.xfFadeDown(XenForo.speed.normal)):(e.slideUp(XenForo.speed.fast),c.xfFadeUp(XenForo.speed.normal,!1,!1,"swing"))};this.setVisibility(!0);d("#AttachmentUploader_"+a.data("uploadtype")).bind({AttachmentQueued:function(b){console.info("Queued file %s (%d bytes).",b.file.name,b.file.size);var c=d("#AttachedFileTemplate").clone().attr("id",
b.file.id);c.find(".Filename").text(b.file.name);c.find(".ProgressCounter").text("0%");c.find(".ProgressGraphic span").css("width","0%");b.isImage&&c.addClass("AttachedImage");c.xfInsert("prependTo",".AttachmentList_"+a.data("uploadtype")+".New",null,i);c.find(".AttachmentCanceller").css("display","block").click(function(){b.swfUpload.cancelUpload(b.file.id);c.xfRemove(null,function(){a.trigger("AttachmentsChanged")},g,"swing")});a.trigger("AttachmentsChanged")},AttachmentUploadProgress:function(a){console.log("Uploaded %d/%d bytes.",
a.bytes,a.file.size);var c=Math.min(100,Math.ceil(a.bytes*100/a.file.size)),e=c+"%",a=d("#"+a.file.id),f=a.find(".ProgressCounter"),j=a.find(".ProgressGraphic");f.text(e);j.css("width",e);c>=100&&a.find(".AttachmentCanceller").prop("disabled",!0).addClass("disabled");j.width()>f.outerWidth()&&f.appendTo(j)},AttachmentUploadError:function(a){var c="";d.each(a.ajaxData.error,function(a,b){c+=b+"\n"});XenForo.alert(c+"<br /><br />"+a.file.name);var e=d("#"+a.file.id),f=e.closest(".AttachmentEditor");
e.xfRemove(null,function(){f.trigger("AttachmentsChanged")},g,"swing");console.warn("AttachmentUploadError: %o",a)},AttachmentUploaded:function(b){if(b.file){var c=d("#"+b.file.id),e=c.find(".AttachmentText"),f=c.find(".Thumbnail");new XenForo.ExtLoader(b.ajaxData,function(){e.fadeOut(XenForo.speed.fast,function(){var a=d(b.ajaxData.templateHtml).find(".AttachmentText");a.xfInsert("insertBefore",e,"fadeIn",XenForo.speed.fast);d(b.ajaxData.templateHtml).find(".Thumbnail").xfInsert("replaceAll",f,null,
i);e.xfRemove();a.find(".itemExtraInput.itemInputs").data("expanded")&&a.find("a.ToggleTrigger.ItemToggleTrigger").click();c.attr("id","attachment"+b.ajaxData.attachment_id)})})}else c=d("#attachment"+b.ajaxData.attachment_id),c.length||new XenForo.ExtLoader(b.ajaxData,function(){var c=d(b.ajaxData.templateHtml),e=c.find(".AttachmentText");c.xfInsert("prependTo",a.find(".AttachmentList_"+a.data("uploadtype")+".New"),null,i);e.data("expanded")&&e.find("a.ToggleTrigger.ItemToggleTrigger").click()});
a.trigger("AttachmentsChanged")}});var f=d.context(this,"setVisibility");d("#QuickReply").bind("QuickReplyComplete",function(){a.find(".AttachmentList.New li:not(#AttachedFileTemplate)").xfRemove(null,f)});a.bind("AttachmentsChanged",f)};XenForo.AttachmentInserter=function(a){a.click(function(d){var b=a.closest(".AttachedFile").find(".Thumbnail a"),c=b.data("attachmentid"),e;e=b.find("img").attr("src");b=b.attr("href");d.preventDefault();a.attr("name")=="thumb"?(d="[ATTACH]"+c+"[/ATTACH] ",e='<img src="'+
e+'" class="attachThumb bbCodeImage" alt="attachThumb'+c+'" /> '):(d="[ATTACH=full]"+c+"[/ATTACH] ",e='<img src="'+b+'" class="attachFull bbCodeImage" alt="attachFull'+c+'" /> ');if(c=XenForo.getEditorInForm(a.closest("form"),":not(.NoAttachment)"))if(c.$editor){c.insertHtml(e);var h=c.$editor.data("xenForoElastic");h&&(setTimeout(function(){h()},250),setTimeout(function(){h()},1E3))}else c.val(c.val()+d)})};XenForo.AttachmentDeleter=function(a){a.css("display","inline-block").click(function(a){var b=
d(a.target),c=b.attr("href")||b.data("href"),e=b.closest(".AttachedFile"),a=b.closest(".AttachedFile").find(".Thumbnail a").data("attachmentid");if(c){e.xfFadeUp(XenForo.speed.normal,null,g,"swing");XenForo.ajax(c,"",function(a){if(XenForo.hasResponseError(a))return e.xfFadeDown(XenForo.speed.normal),!1;var b=e.closest(".AttachmentEditor");e.xfRemove(null,function(){b.trigger("AttachmentsChanged")},g,"swing")});if(a&&(b=XenForo.getEditorInForm(b.closest("form"),":not(.NoAttachment)"))&&b.$editor)b.$editor.find("img[alt=attachFull"+
a+"], img[alt=attachThumb"+a+"]").remove(),(a=b.$editor.data("xenForoElastic"))&&a();return!1}console.warn("Unable to locate href for attachment deletion from %o",b)})};XenForo.AttachmentInsertAll=function(a){a.click(function(){d(".AttachmentInserter[name="+a.attr("name")+"]").each(function(a,b){d(b).trigger("click")})})};XenForo.AttachmentDeleteAll=function(a){a.click(function(){d(".AttachmentDeleter").each(function(a,b){d(b).trigger("click")})})};XenForo.register(".AttachmentDownloader","XenForo.AttachmentDownloader");
XenForo.register(".AttachmentUploader","XenForo.AttachmentUploader");XenForo.register(".AttachmentEditor","XenForo.AttachmentEditor");XenForo.register(".AttachmentInserter","XenForo.AttachmentInserter");XenForo.register(".AttachmentDeleter","XenForo.AttachmentDeleter");XenForo.register(".AttachmentInsertAll","XenForo.AttachmentInsertAll");XenForo.register(".AttachmentDeleteAll","XenForo.AttachmentDeleteAll");XenForo.register(".SetAllTitlesOverlay","XenForo.SetAllTitlesForm");XenForo.register(".InsertFilename",
"XenForo.MediaGallery.InsertFilename");XenForo.register("a.SetAllImageTitles","XenForo.MediaGallery.SetAllImageTitles");XenForo.register("a.SetAllImageDescriptions","XenForo.MediaGallery.SetAllImageDescriptions");XenForo.register("a.SetAllVideoTitles","XenForo.MediaGallery.SetAllVideoTitles");XenForo.register("a.SetAllVideoDescriptions","XenForo.MediaGallery.SetAllVideoDescriptions")})(jQuery,this,document);
