/*
 * XenForo media_embed.min.js
 * Copyright 2010-2015 XenForo Ltd.
 * Released under the XenForo License Agreement: http://xenforo.com/license-agreement
 */
(function(a){XenForo.XenGalleryMediaVideo=function(a){this.__construct(a)};XenForo.XenGalleryMediaVideo.prototype={__construct:function(b){this.$input=b;(this.media_id=b.data("mediaid"))&&a("#VideoPreviewArea").show();if(this.url="index.php?xengallery/preview-video&_xfResponseType=json&media_id="+this.media_id)this.$addButton=a("#AddButton"),this.$addButton.bind({click:a.context(this,"getVideoPreview")}),this.$updateButton=a("#UpdateButton"),this.$updateButton.bind({click:a.context(this,"replaceVideoPreview")}),
a("#VideoPreviewArea").on("click",".DeleteVideo",function(b){b.preventDefault();b=a(b.currentTarget).data("target");a(b).remove();a(".videoEmbed").length||(a("#VideoPreviewArea").xfFadeUp(XenForo.speed.fast),a(".VideoPreviewSubmitUnit").hide());return!1})},getVideoPreview:function(){this.xhr=XenForo.ajax(this.url,{embed_url:this.$input.val(),container_type:a('input[name="container_type"]').val(),container_id:a('input[name="container_id"]').val()},a.context(this,"ajaxSuccess"),{error:"failure"});this.$input.val("")},
replaceVideoPreview:function(){this.xhr=XenForo.ajax(this.url,{embed_url:this.$input.val(),container_type:a('input[name="container_type"]').val(),container_id:a('input[name="container_id"]').val()},a.context(this,"ajaxSuccess"),{error:!1});a(".thumbContainer").remove()},ajaxSuccess:function(b){b.templateHtml?(new XenForo.ExtLoader(b,function(){a("#VideoPreviewArea").xfFadeDown(XenForo.speed.fast);var c=a(b.templateHtml),d=c.find(".AttachmentText");c.xfInsert("prependTo",".VideoPreviewContainer .AttachmentList_video_embed",
"xfShow");d.find(".itemExtraInput.itemInputs").data("expanded")&&d.find("a.ToggleTrigger.ItemToggleTrigger").click()}),a(".VideoPreviewSubmitUnit").show()):(XenForo.alert(b.error),a(".videoEmbed").length||(a("#VideoPreviewArea").xfFadeUp(XenForo.speed.fast),a(".VideoPreviewSubmitUnit").hide()))}};XenForo.register("input.VideoLoader","XenForo.XenGalleryMediaVideo")})(jQuery,this,document);
