/*
 * XenForo media_slider.min.js
 * Copyright 2010-2015 XenForo Ltd.
 * Released under the XenForo License Agreement: http://xenforo.com/license-agreement
 */
(function(c,f){XenForo.XenGalleryCarousel=function(c){this.__construct(c)};XenForo.XenGalleryCarousel.prototype={__construct:function(h){if(!(c.browser.msie&&parseInt(c.browser.version,10)<9)){var k=h.data("target");this.target=c(k);var a=this.target.data("responsive")?!0:!1;this.responsive=a;this.slideWidth=this.target.data("slide-width")?this.target.data("slide-width"):160;this.windowWidth=c(f).width();this.windowHeight=c(f).height();var b=this.getWidthBasedMaxSlides(),g=this.target.data("navigation")?
!0:!1,b=this.target.data("items")?h.data("items"):b,d=this.target.data("responsive-wide")?c.parseJSON("["+h.data("responsive-wide")+"]"):[800,2],n=this.target.data("responsive-medium")?c.parseJSON("["+h.data("responsive-medium")+"]"):[600,2],i=this.target.data("responsive-narrow")?c.parseJSON("["+h.data("responsive-narrow")+"]"):[400,2],j=this.target.data("direction")?this.target.data("direction"):"ltr",o=this.target.data("nav-next"),m=this.target.data("nav-prev");this.window=c(f);typeof m=="undefined"&&
(m='<i class="fa fa-chevron-left fa-3x"></i>');typeof o=="undefined"&&(o='<i class="fa fa-chevron-right fa-3x"></i>');j=="rtl"&&($switchprev=o,$switchnext=m,m=$switchprev,o=$switchnext);c(".thumbContainer").hover(function(){c(this).addClass("showOverlay")},function(){c(this).removeClass("showOverlay")});this.target.length?(this.target.owlCarousel({direction:j,items:b,itemsDesktopSmall:d,itemsTablet:n,itemsTabletSmall:!1,itemsMobile:i,lazyLoad:!0,pagination:!1,navigation:g,navigationText:[m,o],slideSpeed:300,
responsive:a,afterInit:function(){this.target=c(k);this.target.find(".thumbImage").first().bind("load",function(){var a=c(this),b=c(k),d=a.height(),g=b.find(".owl-prev"),b=b.find(".owl-next"),d=Math.floor((d-45)/2);g.css({top:d});b.css({top:d});g.show();b.show();this.complete||a.trigger("load")});h.parents(".xmgCarouselContainer").xfFadeIn();this.target.xfSlideDown()},afterUpdate:function(){var a=c(k),b=a.find(".thumbImage").first().height(),d=a.find(".owl-prev"),a=a.find(".owl-next"),b=Math.floor((b-
45)/2);d.css({top:b});a.css({top:b});d.show();a.show()}}),this.owl=this.target.data("owlCarousel"),this.window.bind({resize:c.context(this,"triggerResize")})):h.hide()}},triggerResize:function(){if(this.responsive){var h=c(f).width(),k=c(f).height();h!=this.windowWidth&&k!=this.windowHeight&&this.owl.reinit({items:this.getWidthBasedMaxSlides()})}},getWidthBasedMaxSlides:function(){var f=c(".mainContent").width();return!this.responsive?void 0:Math.floor(f/this.slideWidth)}};XenForo.register(".XmgCarousel",
"XenForo.XenGalleryCarousel")})(jQuery,this,document);if(typeof Object.create!=="function")Object.create=function(c){function f(){}f.prototype=c;return new f};
(function(c,f,h){var k={init:function(a,b){this.$elem=c(b);this.options=c.extend({},c.fn.owlCarousel.options,this.$elem.data(),a);this.userOptions=a;this.loadContent()},loadContent:function(){function a(a){var g,c="";if(typeof b.options.jsonSuccess==="function")b.options.jsonSuccess.apply(this,[a]);else{for(g in a.owl)a.owl.hasOwnProperty(g)&&(c+=a.owl[g].item);b.$elem.html(c)}b.logIn()}var b=this,g;typeof b.options.beforeInit==="function"&&b.options.beforeInit.apply(this,[b.$elem]);typeof b.options.jsonPath===
"string"?(g=b.options.jsonPath,c.getJSON(g,a)):b.logIn()},logIn:function(){this.$elem.data("owl-originalStyles",this.$elem.attr("style")).data("owl-originalClasses",this.$elem.attr("class"));this.$elem.css({opacity:0});this.orignalItems=this.options.items;this.checkBrowser();this.wrapperWidth=0;this.checkVisible=null;this.setVars()},setVars:function(){if(this.$elem.children().length===0)return!1;this.baseClass();this.eventTypes();this.$userItems=this.$elem.children();this.itemsAmount=this.$userItems.length;
this.wrapItems();this.$owlItems=this.$elem.find(".owl-item");this.$owlWrapper=this.$elem.find(".owl-wrapper");this.playDirection="next";this.prevItem=0;this.prevArr=[0];this.currentItem=0;this.customEvents();this.onStartup()},onStartup:function(){this.updateItems();this.calculateAll();this.buildControls();this.updateControls();this.response();this.moveEvents();this.stopOnHover();this.owlStatus();this.options.transitionStyle!==!1&&this.transitionTypes(this.options.transitionStyle);if(this.options.autoPlay===
!0)this.options.autoPlay=5E3;this.play();this.$elem.find(".owl-wrapper").css("display","block");this.$elem.is(":visible")?this.$elem.css("opacity",1):this.watchVisibility();this.onstartup=!1;this.eachMoveUpdate();typeof this.options.afterInit==="function"&&this.options.afterInit.apply(this,[this.$elem])},eachMoveUpdate:function(){this.options.lazyLoad===!0&&this.lazyLoad();this.options.autoHeight===!0&&this.autoHeight();this.onVisibleItems();typeof this.options.afterAction==="function"&&this.options.afterAction.apply(this,
[this.$elem])},updateVars:function(){typeof this.options.beforeUpdate==="function"&&this.options.beforeUpdate.apply(this,[this.$elem]);this.watchVisibility();this.updateItems();this.calculateAll();this.updatePosition();this.updateControls();this.eachMoveUpdate();typeof this.options.afterUpdate==="function"&&this.options.afterUpdate.apply(this,[this.$elem])},reload:function(){var a=this;f.setTimeout(function(){a.updateVars()},0)},watchVisibility:function(){var a=this;if(a.$elem.is(":visible")===!1)a.$elem.css({opacity:0}),
f.clearInterval(a.autoPlayInterval),f.clearInterval(a.checkVisible);else return!1;a.checkVisible=f.setInterval(function(){a.$elem.is(":visible")&&(a.reload(),a.$elem.animate({opacity:1},200),f.clearInterval(a.checkVisible))},500)},wrapItems:function(){this.$userItems.wrapAll('<div class="owl-wrapper">').wrap('<div class="owl-item"></div>');this.$elem.find(".owl-wrapper").wrap('<div class="owl-wrapper-outer">');this.wrapperOuter=this.$elem.find(".owl-wrapper-outer");this.$elem.css("display","block")},
baseClass:function(){var a=this.$elem.hasClass(this.options.baseClass),b=this.$elem.hasClass(this.options.theme);a||this.$elem.addClass(this.options.baseClass);b||this.$elem.addClass(this.options.theme)},updateItems:function(){var a,b;if(this.options.responsive===!1)return!1;if(this.options.singleItem===!0)return this.options.items=this.orignalItems=1,this.options.itemsCustom=!1,this.options.itemsDesktop=!1,this.options.itemsDesktopSmall=!1,this.options.itemsTablet=!1,this.options.itemsTabletSmall=
!1,this.options.itemsMobile=!1;a=c(this.options.responsiveBaseWidth).width();if(a>(this.options.itemsDesktop[0]||this.orignalItems))this.options.items=this.orignalItems;if(this.options.itemsCustom!==!1){this.options.itemsCustom.sort(function(a,b){return a[0]-b[0]});for(b=0;b<this.options.itemsCustom.length;b+=1)if(this.options.itemsCustom[b][0]<=a)this.options.items=this.options.itemsCustom[b][1]}else{if(a<=this.options.itemsDesktop[0]&&this.options.itemsDesktop!==!1)this.options.items=this.options.itemsDesktop[1];
if(a<=this.options.itemsDesktopSmall[0]&&this.options.itemsDesktopSmall!==!1)this.options.items=this.options.itemsDesktopSmall[1];if(a<=this.options.itemsTablet[0]&&this.options.itemsTablet!==!1)this.options.items=this.options.itemsTablet[1];if(a<=this.options.itemsTabletSmall[0]&&this.options.itemsTabletSmall!==!1)this.options.items=this.options.itemsTabletSmall[1];if(a<=this.options.itemsMobile[0]&&this.options.itemsMobile!==!1)this.options.items=this.options.itemsMobile[1]}if(this.options.items>
this.itemsAmount&&this.options.itemsScaleUp===!0)this.options.items=this.itemsAmount},response:function(){var a=this,b,g;if(a.options.responsive!==!0)return!1;g=c(f).width();a.resizer=function(){c(f).width()!==g&&(a.options.autoPlay!==!1&&f.clearInterval(a.autoPlayInterval),f.clearTimeout(b),b=f.setTimeout(function(){g=c(f).width();a.updateVars()},a.options.responsiveRefreshRate))};c(f).resize(a.resizer)},updatePosition:function(){this.jumpTo(this.currentItem);this.options.autoPlay!==!1&&this.checkAp()},
appendItemsSizes:function(){var a=this,b=0,g=a.itemsAmount-a.options.items;a.$owlItems.each(function(d){var f=c(this);f.css({width:a.itemWidth}).data("owl-item",Number(d));if(d%a.options.items===0||d===g)d>g||(b+=1);f.data("owl-roundPages",b)})},appendWrapperSizes:function(){var a=this.$owlItems.length*this.itemWidth,b;this.options.direction=="rtl"?b={right:0,direction:"rtl"}:b={left:0};this.$owlWrapper.css({width:a*2});this.$owlWrapper.css(b);this.appendItemsSizes()},calculateAll:function(){this.calculateWidth();
this.appendWrapperSizes();this.loops();this.max()},calculateWidth:function(){this.itemWidth=Math.round(this.$elem.width()/this.options.items)},max:function(){var a=(this.itemsAmount*this.itemWidth-this.options.items*this.itemWidth)*-1;this.options.items>this.itemsAmount?this.maximumPixels=a=this.maximumItem=0:(this.maximumItem=this.itemsAmount-this.options.items,this.maximumPixels=a);return a},min:function(){return 0},loops:function(){var a=0,b=0,g,d;this.positionsInArray=[0];this.pagesInArray=[];
for(g=0;g<this.itemsAmount;g+=1)b+=this.itemWidth,this.positionsInArray.push(-b),this.options.scrollPerPage===!0&&(d=c(this.$owlItems[g]),d=d.data("owl-roundPages"),d!==a&&(this.pagesInArray[a]=this.positionsInArray[g],a=d))},buildControls:function(){if(this.options.navigation===!0||this.options.pagination===!0)this.owlControls=c('<div class="owl-controls"/>').toggleClass("clickable",!this.browser.isTouch).appendTo(this.$elem);this.options.pagination===!0&&this.buildPagination();this.options.navigation===
!0&&this.buildButtons()},buildButtons:function(){var a=this,b=c('<div class="owl-buttons"/>');a.owlControls.append(b);a.buttonPrev=c("<div/>",{"class":"owl-prev",html:a.options.navigationText[0]||""});a.buttonNext=c("<div/>",{"class":"owl-next",html:a.options.navigationText[1]||""});b.append(a.buttonPrev).append(a.buttonNext);b.on("touchstart.owlControls mousedown.owlControls",'div[class^="owl"]',function(a){a.preventDefault()});b.on("touchend.owlControls mouseup.owlControls",'div[class^="owl"]',
function(b){b.preventDefault();c(this).hasClass("owl-next")?a.next():a.prev()})},buildPagination:function(){var a=this;a.paginationWrapper=c('<div class="owl-pagination"/>');a.owlControls.append(a.paginationWrapper);a.paginationWrapper.on("touchend.owlControls mouseup.owlControls",".owl-page",function(b){b.preventDefault();Number(c(this).data("owl-page"))!==a.currentItem&&a.goTo(Number(c(this).data("owl-page")),!0)})},updatePagination:function(){var a,b,g,d,f,i;if(this.options.pagination===!1)return!1;
this.paginationWrapper.html("");a=0;b=this.itemsAmount-this.itemsAmount%this.options.items;for(d=0;d<this.itemsAmount;d+=1)d%this.options.items===0&&(a+=1,b===d&&(g=this.itemsAmount-this.options.items),f=c("<div/>",{"class":"owl-page"}),i=c("<span></span>",{text:this.options.paginationNumbers===!0?a:"","class":this.options.paginationNumbers===!0?"owl-numbers":""}),f.append(i),f.data("owl-page",b===d?g:d),f.data("owl-roundPages",a),this.paginationWrapper.append(f));this.checkPagination()},checkPagination:function(){var a=
this;if(a.options.pagination===!1)return!1;a.paginationWrapper.find(".owl-page").each(function(){c(this).data("owl-roundPages")===c(a.$owlItems[a.currentItem]).data("owl-roundPages")&&(a.paginationWrapper.find(".owl-page").removeClass("active"),c(this).addClass("active"))})},checkNavigation:function(){if(this.options.navigation===!1)return!1;this.options.rewindNav===!1&&(this.currentItem===0&&this.maximumItem===0?(this.buttonPrev.addClass("disabled"),this.buttonNext.addClass("disabled")):this.currentItem===
0&&this.maximumItem!==0?(this.buttonPrev.addClass("disabled"),this.buttonNext.removeClass("disabled")):this.currentItem===this.maximumItem?(this.buttonPrev.removeClass("disabled"),this.buttonNext.addClass("disabled")):this.currentItem!==0&&this.currentItem!==this.maximumItem&&(this.buttonPrev.removeClass("disabled"),this.buttonNext.removeClass("disabled")))},updateControls:function(){this.updatePagination();this.checkNavigation();this.owlControls&&(this.options.items>=this.itemsAmount?this.owlControls.hide():
this.owlControls.show())},destroyControls:function(){this.owlControls&&this.owlControls.remove()},next:function(a){if(this.isTransition)return!1;this.currentItem+=this.options.scrollPerPage===!0?this.options.items:1;if(this.currentItem>this.maximumItem+(this.options.scrollPerPage===!0?this.options.items-1:0))if(this.options.rewindNav===!0)this.currentItem=0,a="rewind";else return this.currentItem=this.maximumItem,!1;this.goTo(this.currentItem,a)},prev:function(a){if(this.isTransition)return!1;this.options.scrollPerPage===
!0&&this.currentItem>0&&this.currentItem<this.options.items?this.currentItem=0:this.currentItem-=this.options.scrollPerPage===!0?this.options.items:1;if(this.currentItem<0)if(this.options.rewindNav===!0)this.currentItem=this.maximumItem,a="rewind";else return this.currentItem=0,!1;this.goTo(this.currentItem,a)},goTo:function(a,b,c){var d=this;if(d.isTransition)return!1;typeof d.options.beforeMove==="function"&&d.options.beforeMove.apply(this,[d.$elem]);a>=d.maximumItem?a=d.maximumItem:a<=0&&(a=0);
d.currentItem=d.owl.currentItem=a;if(d.options.transitionStyle!==!1&&c!=="drag"&&d.options.items===1&&d.browser.support3d===!0)return d.swapSpeed(0),d.browser.support3d===!0?d.transition3d(d.positionsInArray[a]):d.css2slide(d.positionsInArray[a],1),d.afterGo(),d.singleItemTransition(),!1;a=d.positionsInArray[a];d.browser.support3d===!0?(d.isCss3Finish=!1,b===!0?(d.swapSpeed("paginationSpeed"),f.setTimeout(function(){d.isCss3Finish=!0},d.options.paginationSpeed)):b==="rewind"?(d.swapSpeed(d.options.rewindSpeed),
f.setTimeout(function(){d.isCss3Finish=!0},d.options.rewindSpeed)):(d.swapSpeed("slideSpeed"),f.setTimeout(function(){d.isCss3Finish=!0},d.options.slideSpeed)),d.transition3d(a)):b===!0?d.css2slide(a,d.options.paginationSpeed):b==="rewind"?d.css2slide(a,d.options.rewindSpeed):d.css2slide(a,d.options.slideSpeed);d.afterGo()},jumpTo:function(a){typeof this.options.beforeMove==="function"&&this.options.beforeMove.apply(this,[this.$elem]);a>=this.maximumItem||a===-1?a=this.maximumItem:a<=0&&(a=0);this.swapSpeed(0);
this.browser.support3d===!0?this.transition3d(this.positionsInArray[a]):this.css2slide(this.positionsInArray[a],1);this.currentItem=this.owl.currentItem=a;this.afterGo()},afterGo:function(){this.prevArr.push(this.currentItem);this.prevItem=this.owl.prevItem=this.prevArr[this.prevArr.length-2];this.prevArr.shift(0);this.prevItem!==this.currentItem&&(this.checkPagination(),this.checkNavigation(),this.eachMoveUpdate(),this.options.autoPlay!==!1&&this.checkAp());typeof this.options.afterMove==="function"&&
this.prevItem!==this.currentItem&&this.options.afterMove.apply(this,[this.$elem])},stop:function(){this.apStatus="stop";f.clearInterval(this.autoPlayInterval)},checkAp:function(){this.apStatus!=="stop"&&this.play()},play:function(){var a=this;a.apStatus="play";if(a.options.autoPlay===!1)return!1;f.clearInterval(a.autoPlayInterval);a.autoPlayInterval=f.setInterval(function(){a.next(!0)},a.options.autoPlay)},swapSpeed:function(a){a==="slideSpeed"?this.$owlWrapper.css(this.addCssSpeed(this.options.slideSpeed)):
a==="paginationSpeed"?this.$owlWrapper.css(this.addCssSpeed(this.options.paginationSpeed)):typeof a!=="string"&&this.$owlWrapper.css(this.addCssSpeed(a))},addCssSpeed:function(a){return{"-webkit-transition":"all "+a+"ms ease","-moz-transition":"all "+a+"ms ease","-o-transition":"all "+a+"ms ease",transition:"all "+a+"ms ease"}},removeTransition:function(){return{"-webkit-transition":"","-moz-transition":"","-o-transition":"",transition:""}},doTranslate:function(a){this.options.direction=="rtl"&&(a=
-a);return{"-webkit-transform":"translate3d("+a+"px, 0px, 0px)","-moz-transform":"translate3d("+a+"px, 0px, 0px)","-o-transform":"translate3d("+a+"px, 0px, 0px)","-ms-transform":"translate3d("+a+"px, 0px, 0px)",transform:"translate3d("+a+"px, 0px,0px)"}},transition3d:function(a){this.$owlWrapper.css(this.doTranslate(a))},css2move:function(a){var b;this.options.direction=="rtl"?b={right:a}:b={left:a};this.$owlWrapper.css(b)},css2slide:function(a,b){var c=this,d;c.options.direction=="rtl"?d={right:a}:
d={left:a};c.isCssFinish=!1;c.$owlWrapper.stop(!0,!0).animate(d,{duration:b||c.options.slideSpeed,complete:function(){c.isCssFinish=!0}})},checkBrowser:function(){var a=h.createElement("div");a.style.cssText="  -moz-transform:translate3d(0px, 0px, 0px); -ms-transform:translate3d(0px, 0px, 0px); -o-transform:translate3d(0px, 0px, 0px); -webkit-transform:translate3d(0px, 0px, 0px); transform:translate3d(0px, 0px, 0px)";a=a.style.cssText.match(/translate3d\(0px, 0px, 0px\)/g);this.browser={support3d:a!==
null&&a.length===1,isTouch:"ontouchstart"in f||f.navigator.msMaxTouchPoints}},moveEvents:function(){if(this.options.mouseDrag!==!1||this.options.touchDrag!==!1)this.gestures(),this.disabledEvents()},eventTypes:function(){var a=["s","e","x"];this.ev_types={};this.options.mouseDrag===!0&&this.options.touchDrag===!0?a=["touchstart.owl mousedown.owl","touchmove.owl mousemove.owl","touchend.owl touchcancel.owl mouseup.owl"]:this.options.mouseDrag===!1&&this.options.touchDrag===!0?a=["touchstart.owl","touchmove.owl",
"touchend.owl touchcancel.owl"]:this.options.mouseDrag===!0&&this.options.touchDrag===!1&&(a=["mousedown.owl","mousemove.owl","mouseup.owl"]);this.ev_types.start=a[0];this.ev_types.move=a[1];this.ev_types.end=a[2]},disabledEvents:function(){this.$elem.on("dragstart.owl",function(a){a.preventDefault()});this.$elem.on("mousedown.disableTextSelect",function(a){return c(a.target).is("input, textarea, select, option")})},gestures:function(){var a,b,g,d,n,i;function j(a){if(a.touches!==void 0)return{x:a.touches[0].pageX,
y:a.touches[0].pageY};if(a.touches===void 0){if(a.pageX!==void 0)return{x:a.pageX,y:a.pageY};if(a.pageX===void 0)return{x:a.clientX,y:a.clientY}}}function k(a){a==="on"?(c(h).on(e.ev_types.move,m),c(h).on(e.ev_types.end,p)):a==="off"&&(c(h).off(e.ev_types.move),c(h).off(e.ev_types.end))}function m(l){l=l.originalEvent||l||f.event;e.options.direction=="rtl"?(e.newPosX=-j(l).x-b,e.newPosY=j(l).y-g,e.newRelativeX=e.newPosX+a):(e.newPosX=j(l).x-b,e.newPosY=j(l).y-g,e.newRelativeX=e.newPosX-a);typeof e.options.startDragging===
"function"&&i!==!0&&e.newRelativeX!==0&&(i=!0,e.options.startDragging.apply(e,[e.$elem]));if((e.newRelativeX>8||e.newRelativeX<-8)&&e.browser.isTouch===!0)l.preventDefault!==void 0?l.preventDefault():l.returnValue=!1,d=!0;(e.newPosY>10||e.newPosY<-10)&&d===!1&&c(h).off("touchmove.owl");e.newPosX=Math.max(Math.min(e.newPosX,e.newRelativeX/5),e.maximumPixels+e.newRelativeX/5);e.browser.support3d===!0?e.transition3d(e.newPosX):e.css2move(e.newPosX)}function p(a){var a=a.originalEvent||a||f.event,b;a.target=
a.target||a.srcElement;i=!1;e.browser.isTouch!==!0&&e.$owlWrapper.removeClass("grabbing");e.dragDirection=e.options.direction=="rtl"?e.newRelativeX<0?e.owl.dragDirection="right":e.owl.dragDirection="left":e.newRelativeX<0?e.owl.dragDirection="left":e.owl.dragDirection="right";if(e.newRelativeX!==0&&(b=e.getNewPosition(),e.goTo(b,!1,"drag"),n===a.target&&e.browser.isTouch!==!0))c(a.target).on("click.disable",function(a){a.stopImmediatePropagation();a.stopPropagation();a.preventDefault();c(a.target).off("click.disable")}),
a=c._data(a.target,"events").click,b=a.pop(),a.splice(0,0,b);k("off")}var e=this;b=0;g=0;a=0;d=null;n=null;i=void 0;e.isCssFinish=!0;e.$elem.on(e.ev_types.start,".owl-wrapper",function(i){var i=i.originalEvent||i||f.event,h;if(i.which===3)return!1;if(!(e.itemsAmount<=e.options.items)){if(e.isCssFinish===!1&&!e.options.dragBeforeAnimFinish)return!1;if(e.isCss3Finish===!1&&!e.options.dragBeforeAnimFinish)return!1;e.options.autoPlay!==!1&&f.clearInterval(e.autoPlayInterval);e.browser.isTouch!==!0&&!e.$owlWrapper.hasClass("grabbing")&&
e.$owlWrapper.addClass("grabbing");e.newPosX=0;e.newRelativeX=0;c(this).css(e.removeTransition());h=c(this).position();e.options.direction=="rtl"?(a=positionRight=e.$owlItems.eq(0).width()*e.currentItem,b=-j(i).x+positionRight):(a=h.left,b=j(i).x-h.left);g=j(i).y-h.top;k("on");d=!1;n=i.target||i.srcElement}})},getNewPosition:function(){var a=this.closestItem();if(a>this.maximumItem)a=this.currentItem=this.maximumItem;else if(this.newPosX>=0)this.currentItem=a=0;return a},closestItem:function(){var a=
this,b=a.options.scrollPerPage===!0?a.pagesInArray:a.positionsInArray,g=a.newPosX,d=null;c.each(b,function(f,i){if(g-a.itemWidth/20>b[f+1]&&g-a.itemWidth/20<i&&a.moveDirection()==="left")d=i,a.currentItem=a.options.scrollPerPage===!0?c.inArray(d,a.positionsInArray):f;else if(g+a.itemWidth/20<i&&g+a.itemWidth/20>(b[f+1]||b[f]-a.itemWidth)&&a.moveDirection()==="right")a.options.scrollPerPage===!0?(d=b[f+1]||b[b.length-1],a.currentItem=c.inArray(d,a.positionsInArray)):(d=b[f+1],a.currentItem=f+1)});
return a.currentItem},moveDirection:function(){var a;this.newRelativeX<0?(a="right",this.playDirection="next"):(a="left",this.playDirection="prev");return a},customEvents:function(){var a=this;a.$elem.on("owl.next",function(){a.next()});a.$elem.on("owl.prev",function(){a.prev()});a.$elem.on("owl.play",function(b,c){a.options.autoPlay=c;a.play();a.hoverStatus="play"});a.$elem.on("owl.stop",function(){a.stop();a.hoverStatus="stop"});a.$elem.on("owl.goTo",function(b,c){a.goTo(c)});a.$elem.on("owl.jumpTo",
function(b,c){a.jumpTo(c)})},stopOnHover:function(){var a=this;a.options.stopOnHover===!0&&a.browser.isTouch!==!0&&a.options.autoPlay!==!1&&(a.$elem.on("mouseover",function(){a.stop()}),a.$elem.on("mouseout",function(){a.hoverStatus!=="stop"&&a.play()}))},lazyLoad:function(){var a,b,g,d,f;if(this.options.lazyLoad===!1)return!1;for(a=0;a<this.itemsAmount;a+=1)b=c(this.$owlItems[a]),b.data("owl-loaded")!=="loaded"&&(g=b.data("owl-item"),d=b.find(".lazyOwl"),typeof d.data("src")!=="string"?b.data("owl-loaded",
"loaded"):(b.data("owl-loaded")===void 0&&(d.hide(),b.addClass("loading").data("owl-loaded","checked")),(f=this.options.lazyFollow===!0?g>=this.currentItem:!0)&&g<this.currentItem+this.options.items&&d.length&&this.lazyPreload(b,d)))},lazyPreload:function(a,b){function c(){a.data("owl-loaded","loaded").removeClass("loading");b.removeAttr("data-src");h.options.lazyEffect==="fade"?b.fadeIn(400):b.show();typeof h.options.afterLazyLoad==="function"&&h.options.afterLazyLoad.apply(this,[h.$elem])}function d(){i+=
1;h.completeImg(b.get(0))||j===!0?c():i<=100?f.setTimeout(d,100):c()}var h=this,i=0,j;b.prop("tagName")==="DIV"?(b.css("background-image","url("+b.data("src")+")"),j=!0):b[0].src=b.data("src");d()},autoHeight:function(){function a(){var a=c(g.$owlItems[g.currentItem]).height();g.wrapperOuter.css("height",a+"px");g.wrapperOuter.hasClass("autoHeight")||f.setTimeout(function(){g.wrapperOuter.addClass("autoHeight")},0)}function b(){h+=1;g.completeImg(d.get(0))?a():h<=100?f.setTimeout(b,100):g.wrapperOuter.css("height",
"")}var g=this,d=c(g.$owlItems[g.currentItem]).find("img"),h;d.get(0)!==void 0?(h=0,b()):a()},completeImg:function(a){return!a.complete?!1:typeof a.naturalWidth!=="undefined"&&a.naturalWidth===0?!1:!0},onVisibleItems:function(){var a;this.options.addClassActive===!0&&this.$owlItems.removeClass("active");this.visibleItems=[];for(a=this.currentItem;a<this.currentItem+this.options.items;a+=1)this.visibleItems.push(a),this.options.addClassActive===!0&&c(this.$owlItems[a]).addClass("active");this.owl.visibleItems=
this.visibleItems},transitionTypes:function(a){this.outClass="owl-"+a+"-out";this.inClass="owl-"+a+"-in"},singleItemTransition:function(){var a=this,b=a.outClass,c=a.inClass,d=a.$owlItems.eq(a.currentItem),f=a.$owlItems.eq(a.prevItem),h=Math.abs(a.positionsInArray[a.currentItem])+a.positionsInArray[a.prevItem],j=Math.abs(a.positionsInArray[a.currentItem])+a.itemWidth/2;a.isTransition=!0;a.$owlWrapper.addClass("owl-origin").css({"-webkit-transform-origin":j+"px","-moz-perspective-origin":j+"px","perspective-origin":j+
"px"});f.css({position:"relative",left:h+"px"}).addClass(b).on("webkitAnimationEnd oAnimationEnd MSAnimationEnd animationend",function(){a.endPrev=!0;f.off("webkitAnimationEnd oAnimationEnd MSAnimationEnd animationend");a.clearTransStyle(f,b)});d.addClass(c).on("webkitAnimationEnd oAnimationEnd MSAnimationEnd animationend",function(){a.endCurrent=!0;d.off("webkitAnimationEnd oAnimationEnd MSAnimationEnd animationend");a.clearTransStyle(d,c)})},clearTransStyle:function(a,b){a.css({position:"",left:""}).removeClass(b);
if(this.endPrev&&this.endCurrent)this.$owlWrapper.removeClass("owl-origin"),this.isTransition=this.endCurrent=this.endPrev=!1},owlStatus:function(){this.owl={userOptions:this.userOptions,baseElement:this.$elem,userItems:this.$userItems,owlItems:this.$owlItems,currentItem:this.currentItem,prevItem:this.prevItem,visibleItems:this.visibleItems,isTouch:this.browser.isTouch,browser:this.browser,dragDirection:this.dragDirection}},clearEvents:function(){this.$elem.off(".owl owl mousedown.disableTextSelect");
c(h).off(".owl owl");c(f).off("resize",this.resizer)},unWrap:function(){this.$elem.children().length!==0&&(this.$owlWrapper.unwrap(),this.$userItems.unwrap().unwrap(),this.owlControls&&this.owlControls.remove());this.clearEvents();this.$elem.attr("style",this.$elem.data("owl-originalStyles")||"").attr("class",this.$elem.data("owl-originalClasses"))},destroy:function(){this.stop();f.clearInterval(this.checkVisible);this.unWrap();this.$elem.removeData()},reinit:function(a){a=c.extend({},this.userOptions,
a);this.unWrap();this.init(a,this.$elem)},addItem:function(a,b){var c;if(!a)return!1;if(this.$elem.children().length===0)return this.$elem.append(a),this.setVars(),!1;this.unWrap();c=b===void 0||b===-1?-1:b;c>=this.$userItems.length||c===-1?this.$userItems.eq(-1).after(a):this.$userItems.eq(c).before(a);this.setVars()},removeItem:function(a){if(this.$elem.children().length===0)return!1;a=a===void 0||a===-1?-1:a;this.unWrap();this.$userItems.eq(a).remove();this.setVars()}};c.fn.owlCarousel=function(a){return this.each(function(){if(c(this).data("owl-init")===
!0)return!1;c(this).data("owl-init",!0);var b=Object.create(k);b.init(a,this);c.data(this,"owlCarousel",b)})};c.fn.owlCarousel.options={direction:"ltr",items:5,itemsCustom:!1,itemsDesktop:[1199,4],itemsDesktopSmall:[979,3],itemsTablet:[768,2],itemsTabletSmall:!1,itemsMobile:[479,1],singleItem:!1,itemsScaleUp:!1,slideSpeed:200,paginationSpeed:800,rewindSpeed:1E3,autoPlay:!1,stopOnHover:!1,navigation:!1,navigationText:["prev","next"],rewindNav:!0,scrollPerPage:!1,pagination:!0,paginationNumbers:!1,
responsive:!0,responsiveRefreshRate:200,responsiveBaseWidth:f,baseClass:"owl-carousel",theme:"owl-theme",lazyLoad:!1,lazyFollow:!0,lazyEffect:"fade",autoHeight:!1,jsonPath:!1,jsonSuccess:!1,dragBeforeAnimFinish:!0,mouseDrag:!0,touchDrag:!0,addClassActive:!1,transitionStyle:!1,beforeUpdate:!1,afterUpdate:!1,beforeInit:!1,afterInit:!1,beforeMove:!1,afterMove:!1,afterAction:!1,startDragging:!1,afterLazyLoad:!1}})(jQuery,window,document);
